kmc-jp/guildbook

lib/plugins/univ_helpers.rb
lib/plugins/univ_plugin.rb
views/univ.haml

とりあえず outdated users を後ろに送って email にリンクをつけた．

displays outdated users below in !univ #15

---

lib/plugins/adduser_plugin.rb

locks when UserRepo#add

---

lib/plugins/adduser_plugin.rb
views/adduser.haml
views/edit.haml
views/layout.haml

Cool な操作性が提供されます．
* bootstrappoyo!!!!
* ミスったときに入力内容が吹っ飛びません！！！
* パスワードの二重チェックをしてくれます！！！！

Cool UX にした！！！！

---

lib/plugins/adduser_plugin.rb

implements check_uid_valid #26

---

lib/ssha.rb

makes salt generation safer

---

lib/user.rb

shows LDAP error message unless success

---

lib/app.rb
lib/plugins/adduser_plugin.rb
views/layout.haml

#37 
Appクラスでnavlinks配列を公開して，プラグインはこれにハッシュを追加していく形にしてみました．
どうでしょうか @t-uda

プラグインからナビゲーションバーにリンクを追加できるようにする

---

config.ru
config/guildbook.yml.example
lib/plugins/help_plugin.rb

#36 
ヘルプページへのリンクを追加するプラグインを書きました． #38 に依存しています．

使い方ページヘのリンクを表示するプラグインを追加

---

config.ru
config/guildbook.yml.example
lib/plugins/help_plugin.rb

#39 は間違えてmasterじゃないブランチに対してプルリクだしてました．

Feature helplink

---

.gitignore
Rakefile
assets/javascripts/app.js
bower.json
lib/app.rb
views/layout.haml

JavaScriptつかいたい機運が高まってきたので，
bowerでいい感じにライブラリを入れられるようにします．

Bowerを導入する

---

lib/user.rb
views/edit.haml

メール転送先を設定できるようにする

---

lib/string_ext.rb
lib/user.rb

学年を全角で入力していてうまくパースできてないケースが意外と多かった

全角数字を半角に変換する

---

views/index.haml

一覧(詳細)に所属の列を追加

---

assets/stylesheets/app.scss
lib/app.rb
lib/plugins/adduser_plugin.rb
lib/user.rb
lib/view_helpers.rb
views/edit.haml

- sshPublicKey を編集できるようにする
- 改行コードは CRLF で送られてくるので LF にそろえている

Edit sshPublicKey

---

lib/plugins/adduser_plugin.rb

Use plus-sign icon for add_user

---

assets/javascripts/adduser-ui.js
assets/stylesheets/app.scss
bower.json
lib/app.rb
views/adduser.haml
views/layout.haml

#25 実装した．
もうちょっとまともに書き直したかったけど段々やる気が失われてきたので，さっさとレビューに回してなんか言われたら直すことにするし．（雑に書いた叩き台コードが割と残ってるぞ！！！）

Password strength meter

---

Gemfile
Gemfile.lock
lib/app.rb

諸事情でJVMのバージョンをあげられず新しいclosure-compilerを使えないので一旦外す

Remove closure compiler

---

assets/javascripts/app.js

Client-side validation of SSH public keys

---

lib/plugins/group_plugin.rb

https://github.com/kmc-jp/guildbook/pull/48 でgroupの時は修正されていなかったのをあてます。

groupでもソートの時数値としてソートする。

---

lib/plugins/checklist_helpers.rb
views/checklist.haml

checklistで作られるテーブルから居なくなった人をコメントアウト

comment out disappeared students

---

views/checklist.haml

remove useless each

---

javascript/packs/app.ts
views/adduser.haml

アカウントを追加するときはよく確認してね

---

javascript/packs/app.ts

zxcvbn これで型つけられるのではないか

---

javascript/packs/app.ts

Reverts kmc-jp/guildbook#90
https://twitter.com/chabezou/status/961225317296701440

Revert "zxcvbn これで型つけられるのではないか"

---

javascript/packs/app.ts
lib/plugins/adduser_plugin.rb

つよいパスワードに文句を言わせない

---

package.json

Lock npm version in package.json

---

views/edit.haml

Clarify that addresses are only visible to other KMC members

---

config/guildbook.yml.example
views/detail.haml

https://github.com/kmc-jp/root-memo/issues/180

Display Slack user ID in detail view

---

config/guildbook.yml.example
lib/plugins/adduser_plugin.rb

`blacklist` を避けるために `login_blacklist` から `login_denylist` に改称しました

login_blacklist → login_denylist

---

views/edit.haml

英字含みの学生番号を許容する

---

.github/workflows/test.yml
lib/md4.rb
lib/ntlm_hash.rb
spec/md4_spec.rb

MD4 is marked as legacy algorithm in OpenSSL and disabled by default now

pure-Ruby MD4
